network:
  game1:
    bind:
      address: 0.0.0.0
      port: 7676
    endpoint:
      address: 172.30.1.34
      port: 7676
  inter_server:
    master_host: 127.0.0.1
    master_port: 6766

config:
  game:
    index: 1
    type:
      - field # field or instance
