network:
  game3:
    bind:
      address: 0.0.0.0
      port: 7678
    endpoint:
      address: 192.168.1.128
      port: 7678
  inter_server:
    master_host: 127.0.0.1
    master_port: 6766

config:
  game:
    index: 3
    type:
      - field # field or instance
      - instance
