network:
  game2:
    bind:
      address: "0.0.0.0"
      port: 7677
    endpoint:
      address: "192.168.1.128"
      port: 7677
  inter_server:
    master_host: "127.0.0.1"
    master_port: 6766

config:
  game:
    index: 2
    type:
      - "instance" # "field" or "instance"
