network:
  game1:
    bind:
      address: "0.0.0.0"
      port: 7677
  inter_server:
    redis_host: "127.0.0.1"
    redis_port: 6379

config:
  game:
    type:
      - "instance" # "field" or "instance"
