max_severity: "verbose" # none
                        # fatal
                        # error
                        # warning
                        # info
                        # debug
                        # verbose
