thread:
  db_accessor_count: 4

network:
  login:
    bind:
      address: "0.0.0.0"
      port: 7675
  inter_server:
    master_host: "127.0.0.1"
    master_port: 6766

config:
  login:
    index: 0

session:
  security:
    max_login_retries: 5 # 세션당 최대 로그인 시도 횟수
